### ISSUE TITLE
User Bday in unix Time

### ISSUE THREAD

**Issue by xDGeForcexD** [DZCP-Community/DZCP-1.6#133]
Hi,

mir ist aufgefallen das seit der 1.6 der Geburtstag als unix Time gespeichert wird. Dies sollte wieder rückgängig gemacht werde da man sonst nur ein alter von max 45 Jahren haben kann weil die unix Time ja erst seit 1.1.1970 gibt.

Bitte beachtet aber das bei der Userliste die Sortier Funktion vom alter weiterhin geht! Deshalb ist dieser Bug glaub ich drin.

Gruß
xDGeForcexD

**Comment by Aviator-Coding** [comment]
Rofl

**Comment by hammermaps** [comment]
Kann ich nicht bestätigen, ich hab mal 5.4.1935 als Geburtstag eingetragen, geht perfekt in der Userliste 79J, auf dem Profil => 05.04.1935, wie ich es angegeben habe, das läuft alles über den Timestamp, wenn es damit ein Problem gäbe, würde das man sofort sehen.

Ich hab es extra umgebaut, da es Probleme mit dem Sortieren gegeben hat, der hat soweit ich weis irgendwann das Datum durcheinander geworfen, aber nur bei bestimmten Daten.

**Comment by xDGeForcexD** [comment]
hm habs grad selbst getestet

da hast du recht es geht doch

der timestamp geht dann halt ins minus^^

dachte das er nur ins plus geht

**Comment by hammermaps** [comment]
nein, - geht auch xD
