### ISSUE TITLE
Problem beim Update auf 1.7

### ISSUE THREAD

**Issue by ckroehnert** [DZCP-Community/DZCP-1.6#134]
Hi,
ich habe versucht die Datenbank auf 1.7 zu bringen, dabei erhalte ich folgenden Fehler:

Fatal error: Call to a member function fetch_assoc() on a non-object in /var/www/pfc-clan.de/DZCP-1.6/inc/database.php on line 28

Kann mir dabei einer helfen?

Gruß
Christian

**Comment by hammermaps** [comment]
Von welcher version?
1.5-1.6.0.x auf die 1.7 oder Neuinstallation? 
Von 1.6.1.x auf 1.7 ist nicht möglich,  nur per Hand oder Neuinstallation. 

:)

**Comment by ckroehnert** [comment]
Jo, ich habe es von 1.6.1.x versucht. Allerdings geht es auch von 1.5-1.6.0.x nicht. Dort komme ich zwar durch die Installation aber, dann erhalte ich im Forum, den Fehler dass die Table 'pfc_clan_bkup.dzcp_positions' fehlt. Also sollte man für 1.7.0 eine Neuinstallation vornehmen?

**Comment by hammermaps** [comment]
Ja, Neuinstallation,  es kann sein das im forum die SQL abfrage noch nicht richtig ist.
Das forum ist noch im total Umbau :)

**Comment by ckroehnert** [comment]
Ja, dass habe ich schon gemerkt ;).
