### ISSUE TITLE
SQL Install duplicate Key

### ISSUE THREAD

**Issue by lobermann** [DZCP-Community/DZCP-1.6#136]
Hallo,

Zeile 1948 im _installer/conf/mysql.php ist eine doppelte ID vergeben.

> (115, 'YaCy', '', '%.*yacybot.*%i', 0, 1),
> (115, 'Trident', '', '%Trident/([0-9.]*)%i', 0, 1);",false,false,true);

**Comment by hammermaps** [comment]
Oh, übersehen. 
Werde ich ändern.

**Comment by lobermann** [comment]
Hatte zeit und hab gleich nen PR gemacht mit dem fix dafür.

**Comment by hammermaps** [comment]
Perfekt

**Comment by hammermaps** [comment]
https://github.com/DZCP-Community/DZCP-1.6/commit/70a5cae8e31af0dcd1b57f25fed49e303fc1f42f
