### ISSUE TITLE
TS-Connection refused

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6#142]
MoinMoin

gerade beim TS editieren gesehen - In der TS-Box und beim klick auf "Teamspeak" wird der TS aber ohne Fehler angezeigt
![ts_debug_fehler](https://cloud.githubusercontent.com/assets/6206060/5781288/b07df24a-9db1-11e4-8662-75244e35cc13.png)

**Comment by 65DirtyHarry** [comment]
Der Port (41144) stimmt mal überhaupt nicht

**Comment by hammermaps** [comment]
Das ist eine Prüfung auf einen TS3 DNS Server, kannst du ignorieren.
