### ISSUE TITLE
Neue Forenposts in Userlobby Linkbug

### ISSUE THREAD

**Issue by ghost** [DZCP-Community/DZCP-1.6#16]
http://www.dzcp.de/forum/?action=showthread&kid=22&id=16196

Problem ist jetzt eingegrenzt, es tritt immer dann auf wenn der Link zum neuen Post oder Thread ein "page=0" beinhaltet.
Dies ist aber anscheinend "random" da es nur in 2 von 6 Test Threads passiert ist. Wir konnten es nicht weiter eingrenzen.

Alle Datein sind mit den aktuellen von Github abgeglichen.

**Comment by hammermaps** [comment]
https://github.com/DZCP-Community/DZCP-1.6/commit/0eaf8fb332354743dc120f6d43a43578c43fabf7
