### ISSUE TITLE
"Line:"292" => Undefined variable: show_"

### ISSUE THREAD

**Issue by ghost** [DZCP-Community/DZCP-1.6#18]
Frische Install mit der aktuellen Github 1.6.4 Version von heute

https://gyazo.com/2eaef7a4f18110386b02c04237e906b3

Wieso is der debug jetzt eigentlich default an? :P

**Comment by ghost** [comment]
Hm, direkt noch das nächste beim Löschen vom Testsquad... 

https://gyazo.com/6f5f9fed003aa21f429b9f799bdb4d72

**Comment by ghost** [comment]
#####################
Support Informationen
#####################

#####################
DZCP Allgemein 
#####################
DZCP Version: 1.6.0.4
DZCP Release: 22.07.2015
DZCP Build: 1604.00.00
DZCP Template: version1.6

#####################
Domain & User
#####################
Domain: xxxx
System/Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0

#####################
Server Versionen
#####################
Server OS: FreeBSD w97.goneo.de 10.0-RELEASE FreeBSD 10.0-RELEASE #7: Fri Jul 11 10:32:28 CEST 2014     root@wm1.goneo.de:/usr/obj/usr/src/sys/GONEO amd64
Webserver: Apache/2.2.29
PHP-Version: 5.5.27 (apa)
MySQL-Server Version: 5.5.42
MySQLi-Protocol Version: 10
MySQLi-Persistente Datenbankverbindung: Off

#####################
Socket-Verbindungen 
#####################
PHP fsockopen: On
PHP allow_url_fopen: On
PHP Sockets: On

#####################
Servereinstellungen
#####################
open_basedir: no value
GD-Version: bundled (2.1.0 compatible)
PHP-Memory Limit: 128M
imagettftext(): existiert
HTTP_ACCEPT_ENCODING: gzip, deflate
file_uploads: On
upload_max_filesize: 20M
sendmail_from: no value
sendmail_path: /usr/sbin/sendmail -t -i -f noreply@xxxxxxx

**Comment by hammermaps** [comment]
Achte auf "Branch: development" du hast die development version 1.6.0.4 die wurde noch nicht veröffentlicht :)
Da ist der Debug standardmäßig an.
