### ISSUE TITLE
String Fehler

### ISSUE THREAD

**Issue by ghost** [DZCP-Community/DZCP-1.6#25]
Nach der Installation beim aufrufen egal welcher Seite ereignet sich folgender Fehler:

Fatal error: Cannot use 'string' as class name as it is reserved in /srv/users/serverpilot/apps/dev/public/portal/inc/bbcode.php on line 982

**Comment by hammermaps** [comment]
Kannst du mir die laufende PHP Version auf deinem Server sagen?
Scheint dass php sich den Klassennamen reserviert, wenn das in einer neuen Version von PHP kommt, muss ich es dringend ändern.

Ich werde es heute Abend nachbessern.

Gruß
Lucas

**Comment by ghost** [comment]
Hi Lucas,
also ich hatte PHP 7.0RC drauf, jetzt hab ich auf PHP 5.6 umgestellt, da funktionierts einwandfrei. Scheint so, als wäre string in RC7 eine vorgefertigte Klasse.

**Comment by hammermaps** [comment]
Möglich, ich habe es auch nur bis 5.6 laufen gehabt.
Fix:
https://github.com/DZCP-Community/DZCP-1.6/commit/bbcedd500fc8f873545f68570e45c933cc9b9bf1

Danke für den Hinweis.

Kurzes Feeback wenn es geht, dann mache ich den Issue hier zu.
