### ISSUE TITLE
Steam

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6#27]
MoinMoin

Neuste Version von hier.

Jetzt kommt:Der Webhoster dieser Seite erlaubt die benötigte Funktion fopen() nicht! wenn ich in die Userliste gucke - Nur bei Steam

**Comment by hammermaps** [comment]
Ist sie denn aktiviert?

**Comment by 65DirtyHarry** [comment]
Moin
Ja ist aktiviert

**Comment by Microgamer** [comment]
Bei welchem Webhoster bist du denn?

**Comment by 65DirtyHarry** [comment]
Bei Hetzner liegt die HP und bei Colorhost der TS-3
