### ISSUE TITLE
Aktuelle git Version nicht installierbar

### ISSUE THREAD

**Issue by ghost** [DZCP-Community/DZCP-1.6#29]
Aktuelle git Version nicht installierbar, 

kann diese Anfrage momentan nicht verarbeiten. 500

**Comment by hammermaps** [comment]
Habe einen doppelten Eintrag gefunden und beseitigt, bei mir ging das Installieren und aufrufen der Seite problemlos.
Probiere die Installation mit der neuen version.php, wenn es immer noch nicht geht, muss es etwas bei dir sein, ich habe das ganze auf einem Ubuntu-Server Linux mit Apache/PHP 7 und MariaDB 10 getestet.

**Comment by ghost** [comment]
Fatal error: Class '\phpFastCache\Drivers\apc' not found in /web/1/000/085/887/350302/htdocs/new/inc/phpfastcache/CacheManager.php on line 91

**Comment by hammermaps** [comment]
Bitte neu runterladen, bei machen hostern geht der autoload nicht richtig.
