### ISSUE TITLE
No Content after migration to php7

### ISSUE THREAD

**Issue by robingroppe** [DZCP-Community/DZCP-1.6#30]
After migration to Ubuntu Xenial with php7 our dzcp instance shows no content anymore.
Any ideas?

adiosamigos.eu

**Comment by hammermaps** [comment]
Have you a error log?
Set in inc/config.php -> define('view_error_reporting', false);
to 
define('view_error_reporting', true);

Run your page and past the errors here.

**Comment by robingroppe** [comment]
https://www.robingroppe.de/zerobin/?7e29b7380d0fabf9#RWYx3UvteT7KhtT1bVneaie8krShYVaIMaC/F5Qa7L0=

**Comment by robingroppe** [comment]
Just saw that the /gameserver page throws even more.
I will leave error reporting switched on, then you can see it live.

**Comment by hammermaps** [comment]
Please replace the inc/teamspeak_query.php with this file: https://raw.githubusercontent.com/DZCP-Community/DZCP-1.6/development/inc/teamspeak_query.php

The Github Version has fixes for PHP 7 but has not yet been officially released on dzcp.de.

**Comment by robingroppe** [comment]
Is it the same case for the bbcode and gameserverquery?

**Comment by hammermaps** [comment]
Do you speak German?
That would be easier :)

The bbcode and gameserver query is not so easy.

**Comment by robingroppe** [comment]
Jawohl. ;)

Am 11.10.2016 15:07 schrieb "Lucas" notifications@github.com:

**Comment by robingroppe** [comment]
Okay, der TS-Viewer funktioniert schonmal.
Ich ziehe die Seite erstmal auf einen anderen Server um bis das hier gelöst ist.

**Comment by hammermaps** [comment]
Du könntest auch die github version probieren, die sollte auf php 7 laufen, müsstest nur deine addons/mods neu einbauen, wenn du was an der bbcode geändert hast.

**Comment by robingroppe** [comment]
Okay, das probiere ich mal.

**Comment by robingroppe** [comment]
Okay, klasse das funktioniert soweit schonmal. Wow, ist php7 schnell. 8)
Einige Dinge fallen aber noch auf:
- Folgende Seite nach dem einloggen: https://www.robingroppe.de/screens/3c941c898a20083907e9d05b5540e4320df76ca9.png
- Seltsame Zeichen in allen News und eigen anderen Seiten. Zeichencodierung geändert?
  https://www.robingroppe.de/screens/854f1069792cc18d4f129cc62eb3875c2e7cbb01.png
- Nur ein Gameserver auf der richtigen Gameserverseite aber alle sechs in der "Gameserversidebar" + ein ganzer Haufen Hinweise.
  https://www.robingroppe.de/zerobin/?475673a0b7ebc61c#PO61ipnxgnuRB5nBzQEFazm3Jru+Fhmty7gh52nhpI8=
- Teamspeakseite wirft Hinweise:
  https://www.robingroppe.de/zerobin/?46600cd989fc0f73#aONBxvga8ujFjeZnQvFe5hXi2GsI2bLkVLoyl+1UK8I=

**Comment by hammermaps** [comment]
Bei dem Login müsste man mal in die log files schauen im inc/_logs da sollte ein Datei drin sein die deine SQL-Errors loggt.

Zeichenkodierung ist ein leidiges Thema, die sollte auf utf8 laufen, alte dzcp Versionen haben aber eine Mischung verwendet, was jetzt Probleme macht, da müsste man das Zeichen suchen und gegen  HTML/UTF8 codiertes Zeichen austauschen, das habe ich aber noch nicht überall gemacht, darum ist das update noch nicht auf dzcp.de erhältlich.

Zu den Hinweisen, die werden / wurde erst in der 1.7 beseitigt bzw. neu geschrieben, da dzcp sehr alten Code dafür verwendet, das wird später ersetzt.
