### ISSUE TITLE
Es kommen keine E-Mail von DZCP.DE an! // Update Anleitung von 1.5.5.4 zu 1.6?

### ISSUE THREAD

**Issue by digloz** [DZCP-Community/DZCP-1.6#39]
**Hallo!**

Wollte Euch mal darauf aufmerksam machen, dass man bei der offiziellen DZCP Seite keine E-Mails bekommt. Habe nun x mal versucht mein Passwort zu ändern, aber es kommen keine E-Mails an. Habe inzwischen auch versucht einen neuen Account anzulegen, aber auch hier kommt keine E-Mail (und somit auch kein Passwort) an > habe extra verschiedene Anbieter probiert.

Des Weiteren ist es nicht möglich über Euer Kontaktformular auf der Seite mit Euch zu kommunizieren, da der Sicherheitscode nicht angezeigt wird.

Habe vergebens nach einer Anleitung gesucht die einem sagt was in der Version 1.6 gegenüber der 1.5.5.4 alles geändert worden ist. In der Readme steht nur, dass man einfach alles überschreiben soll. Toll ... oder eher nicht, denn wir haben ein maßgeschneidertes Template mit einer Vielzahl (mehr als 30) an Addons (darunter auch welche, die extra für uns geschrieben worden sind) - wir können es nicht einfach alles überbügeln; da dadurch alle Änderungen gelöscht werden. Ich bin mir sicher, dass es hier mehrere betroffene gibt... kaum einer nutzt die Seite ohne individuelle Anpassungen oder ohne Addons.

Ich würde DZCP schon gern weiterhin nutzen, habe aber keine Lust dermaßen viele Dateien zu prüfen wo was neues hinzugekommen (sein könnte) oder eine Zeile (wenn auch nur minimal) geändert worden ist. Bei der ganzen Mühe die das ausmachen würde, könnten wir bereits das Design an ein anderes CMS anpassen; was gar nicht unser Ziel ist - aber rein vom Aufwand dem ganzen Nahe kommt. Zudem wohl der Wechsel von 1.6 zu 1.7 nochmal ein riesiger Schritt (und somit ggf. wieder kein fließender Übergang möglich ist?) wäre...

Wäre hier über Hilfe dankbar.

**Gruß, digloz**

__
@acecom @hammermaps @Koma83

**Comment by hammermaps** [comment]
Danke für deine Hinweise, das mit dem Code und E-Mails sollte nun gehen.
Wir haben für die 1.6 keine Anleitung mehr gemacht, da mehrere Tausend Zeilen für die 1.6 geändert wurden.
Das ist einfach zu viel um eine Anleitung zu schreiben.
Ich werde das erst mit einer späteren Version von DZCP per Patchfiles machen, die automatisch generiert werden, da aktuell alles per Hand gemacht wird, das ist zu viel Arbeit für mich anleine.
Bleibe erstmal bei der 1.5.5.4 da die 1.7 auch nochmal komplett überholt wird, aber erst wenn ich eine laufende Basis auf DZCP.de laufen habe, da mir auch Tester mit Fachwissen fehlen um das anders zu machen.

Sry :(
