### ISSUE TITLE
Platzhalter werden nicht richtig angezeigt

### ISSUE THREAD

**Issue by xero-ru** [DZCP-Community/DZCP-1.6#40]
beim umstellen der cmd Sprache auf russisch werden im Profil nicht alle Platzhalter richtig angezeigt

1. http://www.deine-hp.de/user/?set_language=russian
2. http://www.deine-hp.de/user/?action=editprofile

$language_text['_profil_drink'] = 'Напиток';
$language_text['_profil_essen'] = 'Пища';
$language_text['_profil_film'] = 'Фильм';...
usw. werden als Fragezeichen ausgelesen

 http://www.deine-hp.de/user/server/
Alle Sonderzeichen im Servernamen werden auch mit ?????? angezeigt.

**Comment by hammermaps** [comment]
Sonderzeichen bei Servernamen wird erst mit GameQ geändert.
