### ISSUE TITLE
Neuen User anlegen

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6#49]
MoinMoin

Beim anlegen eines neuen Users und klick auf "Registrieren" passiert nichts - Überhaupt nichts.

"WARNUNG:' /vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php '" | "Line:"236" => The "Zendshm" driver is unavailable at the moment, the fallback driver "Files" has been used instead."
-- | --
"HINWEIS:' /admin/menu/adduser.php '" | "Line:"10" => Undefined variable: bdayday"
"HINWEIS:' /admin/menu/adduser.php '" | "Line:"11" => Undefined variable: bdaymonth"
"HINWEIS:' /admin/menu/adduser.php '" | "Line:"12" => Undefined variable: bdayyear"
"HINWEIS:' /admin/menu/adduser.php '" | "Line:"29" => Undefined index: edit"
"HINWEIS:' /admin/menu/adduser.php '" | "Line:"29" => Undefined index: edit"
"HINWEIS:' /admin/menu/adduser.php '" | "Line:"29" => Undefined index: edit"
"HINWEIS:' /admin/menu/adduser.php '" | "Line:"29" => Undefined index: edit"
"HINWEIS:' /admin/menu/adduser.php '" | "Line:"39" => Undefined index: edit"
"HINWEIS:' /admin/menu/adduser.php '" | "Line:"49" => Undefined variable: esquads"
"HINWEIS:' /admin/menu/adduser.php '" | "Line:"76" => Undefined variable: get"

Gruß Harry

**Comment by hammermaps** [comment]
Klappt problemlos.

**Comment by 65DirtyHarry** [comment]
Siehe Antwort in #51
