### ISSUE TITLE
Membermap & TS

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6#51]
Beim Aufruf der Mambermap kommt.
Hoppla! Ein Fehler ist aufgetreten.
Google Maps wurde auf dieser Seite nicht richtig geladen. Technische Details dazu entnimmst du der JavaScript-Konsole.

Beim Aufruf von http://dzcpbeta.dbm-clan.net/teamspeak/
kommen jede Menge Fehler - Und es wird nichts angezeigt.
Nach mehrmaligem Refreshen wird der TS angezeigt

**Comment by hammermaps** [comment]
Ich würde deine Seite mal vollständig neu aufsetzen.

**Comment by 65DirtyHarry** [comment]
Würde ich ja gern, aber 19 Member haben sich bereits Registriert u. die WILL ich mitnehmen/Importieren und nicht das sie sich NOCHMALS neu Registrieren müssen

**Comment by hammermaps** [comment]
Dir ist klar, das es hier um das Entwiklungs-Zweig handelt und die Version nicht für den produktiven Einsatz gedacht ist.
Da kann ich keine Rücksicht auf deine Datenbank nehmen, es wird kein Upgrade von einer DEV Version auf eine Final geben.
Du müsstest jede Änderung händisch von github auf deine Seite übertragen.

**Comment by 65DirtyHarry** [comment]
MoinMoin.

Klar ist mir das klar, aber ihr habt geschrieben das die Version getestet werden muss u. ihr darum bittet mitzuhelfen auch wenn sie z.Zt. noch nicht für den produktiven Einsatz gedacht ist.

Wie denkt ihr denn das Vernünftig getestet werden soll ?? Soll ich ALLEINE was weiss ich wieviele User/Member anlegen, das Forum füllen - An/Abmelden, anderen User annehmen, Voten, Teamerstellen u. Member zuweisen, Downloads anlegen u. immer wieder nen Member/User mit neuen Rängen testen den User wieder wechseln und so weiter und so weiter ?

Ich habe ganz vernünftig gefragt ob man mir wenigstens beim Import der User/Member die sich schon Registriert haben helfen kann, wie ich die JETZT aktuellste Version nehme u. meine Memberliste in die gerade aktuellste Version Importiere - Sonst stelle ich das Testen / Feedback ein - Ihr braucht das Feedback und so wie ich das sehe bin ich scheinbar der einzige der euch das gerade liefert.

Also, ich ja gern bereit weiterhin meine Freizeit zum Testen u. Feedback geben zu Opfern, aber nicht zu dem Preis das man mir nicht helfen will !

Eine Hand wäscht die andere und zwei ein ganzes Gesicht.
Ich erwarte das man mir hilft auch wenn es sich um einen "Entwicklungszweig" handelt.
Keine Hilfe, dann werde ich zwar die Version weiter einsetzten aber ihr werdet Null Feedback und oder irgendwelche Bugreports mehr bekommen.

Ich war IMMER der erste der jede neue DZCP-Version , jeden Mod u.jedes AddOn getestet hat und euch Feedback gegeben hat - Ich habe euch all meine AddOn's / Mod's (55) zukommen lassen und so dankt ihr (du) es mir ?
Ich bitte nochmals darum mir beim Import der 19 registrierten Member von DZCP Version: 1.6.1.0 / Release: 01.06.2018 / Build: 1610.00.00 / == API ERROR == in die neuste Version zu helfen.

**Comment by hammermaps** [comment]
Verstehe das bitte nicht falsch, wir/ich sind dir sehr dankbar, dass du das Testest und Feedback gibst.
Dass es nicht schaffbar ist, alles alleine zu Testen usw. damit hast du natürlich völlig recht.

Das Importieren ist grundsätzlich immer möglich, nur muss das von jemanden gemacht werden, der sich  mit der Datenbank von DZCP und dem PHP-Backend auskennt, die muss manuell geändert werden.
Ich werde dir später auch helfen die Daten/Datenbank in eine Finale Version zu übernehmen, damit du nicht neu installieren musst.
Sry, ich hatte das etwas Rabiat ausgedrückt :(

Ich möchte nur verhindern, dass sich die Leute die DEV installieren und davon ausgehen das es später einen Updater dafür geben wird, dann ist die Enttäuschung groß wenn es nicht mehr möglich ist, weil bereits alles verändert ist.
Der Updater kann leider nur einmal von 1.6.0.x nach 1.6.1.0 Updaten, dabei kann das nicht rückgängig gemacht werden, ohne die Inhalte der Tabellen zu beschädigen oder unbrauchbar zu machen.

Darum schließe ich von Anfang an Upgrades von DEV-Versionen auf Finale aus, das wäre sonnst für mich nicht mehr schaffbar, wenn ich das bei jedem per Hand helfen müsste.
Bei 3-4 Installationen die ich simultan bearbeiten müsste und der Menge einiger Änderungen die gemacht wurden, kann das Tage dauern.

Es würde zudem viel Chaos bei den Issues bzs. Reports bedeuten, ihr schreibt einen Bug, habt den zbs. mit Mods eingebaut oder hat nicht alle Änderungen übernommen usw.
Das kostet mich manchmal einen ganzen Abend, das möchte ich möglichst verhindern.

Ich aktualisiere deine Seite gerne mit, wenn ich etwas Bugs-Fixe.
DirtyHarry ich bedanke mich für deine Hilfe, ich habe das Problem mit Team-Anzeige und Versionsanzeige (Linux: apt upgrade war schuld :) ) beseitigt, die anderen habe ich noch nicht geschafft, werde die aber mir die die Tage anschauen.
