### ISSUE TITLE
Newskommentare zitieren

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6#52]
Newskommentare zitieren steigt mit nem Hoppla ..... aus
Also habe ich einen Kommentar kommentieren wollen - Der erste Kommentar war lesbar, diesen wollte ich zitieren - Hoppla ... - Dann wollte ich den ersten Kommentar, kommentieren und nun ist der erste Kommentar nach erscheinen der News weg

und ein vorhergehender Kommentar wir nach meinem Kommentar nicht mehr angezeigt

**Comment by 65DirtyHarry** [comment]
OK. Das sollte sich mal jemand anschauen - Threads gleiches Prob.

**Comment by hammermaps** [comment]
Bitte die inc\_logs\sql_error_log.log und welche dzcp Version du genau benutzt, also das datum des Downloads hier auf github

**Comment by hammermaps** [comment]
Konnte das im Forum Reproduzieren "/forum/?action=post&do=addpost&kid=1&id=1" bewirkt ein SQL-Fehler.
Wo wolltest du einen Kommentar kommentieren?
Bei news habe ich nichts gefunden.
