### ISSUE TITLE
Klapptext

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6#6]
MoinMoin.

Der Klapptext bei den News wird schon geöffnet angezeigt - Das ist in der 1.6.x und 1.7. so.

Weiterhin finde ich das ein "Edit-Button"  wie bei den Threads für die News eingebaut werden sollte da man sich so den Weg über das Adminmenü spart.

**Comment by 65DirtyHarry** [comment]
Push

**Comment by ghost** [comment]
Klasse Idee

**Comment by hammermaps** [comment]
Werde es nahher mal anschauen und einbauen

**Comment by 65DirtyHarry** [comment]
MoinMoin

Klapptext sowie News Editieren Button gehen !

Danke

**Comment by hammermaps** [comment]
Hoffe ich doch das es geht ;)
