### ISSUE TITLE
Membermap

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6#60]
Das steht da. 

Google Maps kann auf dieser Seite nicht richtig geladen werden.
Do you own this website?

**Comment by 65DirtyHarry** [comment]
Jetzt bleibt der Inhalt der Map Weiss (https://dbmfc.de/membermap/)

**Comment by tobim91** [comment]
Ich würde ja etwas mit Open Street Map empfehlen, wenn man unbedingt auf dieses Feature Member Map steht, Der Grund warum das kommt soll ja sein das Google ja nur Geld verdienen will und man 1000 Abfragen oder so gratis bekommt und alle mehr bezahlen muss.

**Comment by hammermaps** [comment]
Ja dass ist bekannt, nur das einbinden von Open Street Map ist etwas schwierig da ich immerwieder probleme mit dzcp bekomme, da Open Street Map völlig anders eingebunden wird.
Aktuell habe ich mehr Schwierigkeiten als es löst, zudem Thema Datenschutz muss berücksichtigt werden.
Aktuell ist das für mich eher uninteressant, da ich noch genug Baustellen offen habe :)

Aber danke für deine Hilfe :)

**Comment by netzjunkie** [comment]
Muss noch was am Design gemacht werden?

**Comment by hammermaps** [comment]
Meiste ist JS, html und css ist kaum was.

**Comment by hammermaps** [comment]
Wurde über eine neue API der Seite DZCP.de gelöst.
