### ISSUE TITLE
Userliste / Teams

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6#64]
In der Userliste befinden sich 2 Member u. in Teams steht:Wir sind insgesamt 3 Member und besitzen 1 Team(s)

Wenn ich das Team öffne werden dann die 2 Member angezeigt

**Comment by hammermaps** [comment]
Wie viel member hat das Team?  2 oder 3?

**Comment by 65DirtyHarry** [comment]
2

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by 65DirtyHarry** [comment]
Gerade die neuste über das update gemacht und dann kommt in der Userliste und bei Teams das hier.

Fatal error: Uncaught TypeError: Argument 1 passed to get_elapsed_time() must be of the type integer, null given, called in /usr/www/users/dbmhcl/inc/ajax.php on line 60 and defined in /usr/www/users/dbmhcl/inc/bbcode.php:2699 Stack trace: #0 /usr/www/users/dbmhcl/inc/ajax.php(60): get_elapsed_time(NULL, 1528869529, 1) #1 /usr/www/users/dbmhcl/inc/ajax.php(74): steamIMG('dirtyharry1965') #2 {main} thrown in /usr/www/users/dbmhcl/inc/bbcode.php on line 2699

**Comment by 65DirtyHarry** [comment]
Kann geschlossen werden - Userliste und Teamliste stimmen überein. Tut mir leid. Es wurde bei einigen Membern vergessen sie in das Team einzutragen.
