### ISSUE TITLE
Neuen Newskommentar schreiben

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6#66]
Wenn ich einen neuen Newskommentar schreiben will und auf "Vorschau" gehe kommt.

Fatal error: Uncaught TypeError: Argument 2 passed to cut() must be of the type integer, string given, called in /usr/www/users/dbmhcl/inc/bbcode.php on line 1877 and defined in /usr/www/users/dbmhcl/inc/bbcode.php:1108 Stack trace: #0 /usr/www/users/dbmhcl/inc/bbcode.php(1877): cut('[DBMFC]65DirtyH...', '', false, false) #1 /usr/www/users/dbmhcl/news/case_compreview.php(43): cleanautor(1) #2 /usr/www/users/dbmhcl/news/index.php(80): require_once('/usr/www/users/...') #3 {main} thrown in /usr/www/users/dbmhcl/inc/bbcode.php on line 1108

**Comment by hammermaps** [comment]
Hast du die bbcode.php von gestern abend auf github verwendet?
Die ist nicht fertig gewesen, ich hatte dir gestern Abend eine ältere drauf gelassen, da du noch mehr Probleme bekommst wenn du die von gIT verwendest. 
Bitte nicht die Seite selber akualisieren, ich mache das immer, wie ich das versprochen hatte, bitte lade die alte bbcode.php hoch.

Sofern es sich um http://dbmfc.de/news/ handelt.

**Comment by 65DirtyHarry** [comment]
Soll ich dann das Backup der Dateien u.der DB von heute ca. 02:00 einspielen ?

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by hammermaps** [comment]
Ja kannst du machen
