### ISSUE TITLE
Profilfeld

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6#7]
Beim anlegen eines neuen Profilfeldes zb. BFP4F-Account verschwindet der Bindestrich - Ergebnis BFP4FAccount
Auch wenn ich statt des (minus) ein leerzeichen mache ist das Ergebnis BFP4FAccount

**Comment by acecom** [comment]
Das Problem müsste dann auch andere Sonderzeichen betreffen wie + _

**Comment by 65DirtyHarry** [comment]
Ja, gerade den (_) Unterstrich probiert - das gleiche

**Comment by 65DirtyHarry** [comment]
Lüppt

**Comment by hammermaps** [comment]
Danke für dein Feedback
