### ISSUE TITLE
Emailvorlagen

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6#72]
MoinMoin. Wollte vor/über den Text der zb. Regiestrierungsmail unser Claanlogo einfügen - über Bild einfügen (liegt im Bilder Verzeichnis).

Es wird bis zum abspeichern angezeigt - Beim nochmaligen aufrufen der Emailvorlagen ist das Bild wieder weg.

**Comment by hammermaps** [comment]
https://github.com/DZCP-Community/DZCP-1.6/commit/d9186ed94fed7888ea09d8b3c2da51a88f90290f
