### ISSUE TITLE
Teamspeak

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6#77]
Fatal error: Uncaught Error: Call to undefined function time_convert() in /usr/www/users/dbmfca/teamspeak/index.php:253 Stack trace: #0 {main} thrown in /usr/www/users/dbmfca/teamspeak/index.php on line 253

**Comment by hammermaps** [comment]
https://github.com/DZCP-Community/DZCP-1.6/commit/a197e7e16e23b3500371388f5d6d31bef2eca3a0
