### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by freezer83** [DZCP-Community/DZCP-1.6#78]
Wenn ich die sicherheitsabfrage an stelle, wird mir keine zahl oder ähnliches angezeigt.somit kann ich mich auch nicht anmelden und müsste jetzt noch dzcp neuinstallieren.Das würde ich gerne verhindern wenn mir einer sagen könnte was vielleicht geändert werden müsste.
![inkedscreenshot 2018-07-13 20 13 41_li](https://user-images.githubusercontent.com/41206539/42707293-06a79008-86da-11e8-9a73-8d18e6818f17.jpg)

**Comment by hammermaps** [comment]
Das ist ein Problem, ich werde das laufe der 
kommenden Woche mal genau anschauen.
Du musst über phpmyadmin einen Wert in der Tabelle dzcp_config auf 0 stellen.
Stelle "securelogin" auf "0", dann ist es weg bis ich es geändert habe.
Gruß Lucas
