### ISSUE TITLE
Clanwarkommentare

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6#79]
Habe in einem CW einen Kommentar geschrieben und in der Userlobby wird 0 neue Clanwarkommentare angezeigt.
![clanwarkommentare_fehler_userlobby](https://user-images.githubusercontent.com/6206060/43209048-054bfe50-902c-11e8-956a-eb65e6581b56.png)

**Comment by hammermaps** [comment]
Hast du vorher den User gewechselt?
Wenn du einen Kommentar schreibst, wird dieser nicht in deiner Lobby als neu angezeigt, sondern nur Usern die nicht mehr Aktiv gewesen sind.

**Comment by 65DirtyHarry** [comment]
Denke nicht. Aber OK. Gut zu wissen

BTW. Könntest du bitte mal nach der Aktivitätsliste gucken ? Das kann nicht stimmen
