### ISSUE TITLE
THREAD EDITIEREN

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6#81]
Beim editieren werden HTML-Codes angezeigt und eine Vorschau ist auch nicht mehr möglich. Speichere ich, dann wird der Post aber "Normal" angezeigt, ohne Codes und mit Absätzen

<br />Tierstufe:8-10<br /><br /><br /><br /></span></p>

**Comment by hammermaps** [comment]
Tierstufe:8-10 ?

**Comment by hammermaps** [comment]
Ist außerdem ein Filter fehler drin, Umbrüche usw. gehen nicht richtig.
